import { AzdoClient, WorkItem } from './azdoClient';

export interface ProposedTest {
    title: string;
    description?: string;
    steps: string[];
    pbiId: number;
    tags?: string[]; // e.g. ['Smoke', 'Critical', 'Sanity']
    areaPath?: string;
    iterationPath?: string;
}

export class TestPlanService {
    constructor(private client: AzdoClient) { }

    /**
     * Publishes a batch of tests to Azure DevOps.
     * intended to be called ONLY after user confirmation.
     */
    async publishTestPlan(tests: ProposedTest[]): Promise<number[]> {
        const createdIds: number[] = [];

        // Optional: Pre-fetch project structure logic could go here if we wanted to
        // validate paths before creation. for now we trust the inputs or defaults.

        for (const test of tests) {
            try {
                const id = await this.createTestCase(test);
                createdIds.push(id);
            } catch (error) {
                console.error(`Failed to publish test: ${test.title}`, error);
            }
        }
        return createdIds;
    }

    /**
     * Fetches standard template fields (Areas, Iterations) to present to the user for selection.
     */
    async getTemplateOptions(): Promise<{ areas: string[], iterations: string[] }> {
        return await this.client.getClassificationNodes();
    }

    private async createTestCase(test: ProposedTest): Promise<number> {
        // 1. Create the Work Item with Standard Template Fields
        const fields: any = {
            'System.Title': test.title,
            'System.WorkItemType': 'Test Case',
            'System.Description': test.description || 'Generated by AI PBI Analyzer',
            'Microsoft.VSTS.TCM.Steps': this.formatStepsToXml(test.steps),
            'System.State': 'Design'
        };

        // Apply Standard Template Fields if provided
        if (test.areaPath) fields['System.AreaPath'] = test.areaPath;
        if (test.iterationPath) fields['System.IterationPath'] = test.iterationPath;

        // Apply Tags (Smoke, Critical, Sanity)
        if (test.tags && test.tags.length > 0) {
            fields['System.Tags'] = test.tags.join('; ');
        }

        const workItem = await this.client.createWorkItem('Test Case', fields);

        // 2. Link to PBI
        await this.linkToPbi(workItem.id, test.pbiId);

        return workItem.id;
    }

    private async linkToPbi(testId: number, pbiId: number) {
        // This requires a specific JSON patch for relations
        await this.client.addRelation(testId, {
            rel: 'Microsoft.VSTS.Common.TestedBy-Reverse',
            url: await this.client.getWorkItemUrl(pbiId),
            attributes: { comment: 'Auto-generated Coverage' }
        });
    }

    private formatStepsToXml(steps: string[]): string {
        // Azure DevOps uses an XML format for test steps
        let xml = '<steps id="0" last="' + steps.length + '">';
        steps.forEach((step, index) => {
            xml += `<step id="${index + 1}" type="ValidateStep"><parameterizedString isformatted="true">${step}</parameterizedString><parameterizedString isformatted="true">Expect Success</parameterizedString></step>`;
        });
        xml += '</steps>';
        return xml;
    }
}
