import { TestScenario } from './TestScenarioGenerator';

export class PlaywrightGenerator {
    public generate(title: string, scenarios: TestScenario[]): string {
        const safeTitle = title.replace(/'/g, "\\'");

        const lines: string[] = [];
        lines.push(`// Playwright Pseudo-code for: ${title}`);
        lines.push(`// Generated by Azure DevOps PBI Analyzer`);
        lines.push(`// Framework: Playwright (JavaScript)`);
        lines.push('');
        lines.push(`const { test, expect } = require('@playwright/test');`);
        lines.push('');

        // Filter to smoke and critical only
        const targetScenarios = scenarios.filter(
            (s) => s.tag === 'smoke' || s.tag === 'critical'
        );

        if (targetScenarios.length === 0) {
            lines.push('// No smoke or critical scenarios identified.');
            lines.push(`// All ${scenarios.length} scenario(s) tagged as non-regression.`);
            return lines.join('\n');
        }

        lines.push(`test.describe('${safeTitle}', () => {`);
        lines.push('');
        lines.push(`  test.beforeEach(async ({ page }) => {`);
        lines.push(`    // TODO: Replace with actual application URL`);
        lines.push(`    await page.goto('/');`);
        lines.push(`  });`);
        lines.push('');

        targetScenarios.forEach((scenario) => {
            const safeScenarioTitle = scenario.title.replace(/'/g, "\\'");
            const tagAnnotation = scenario.tag === 'critical'
                ? `  // @critical\n`
                : `  // @smoke\n`;

            lines.push(tagAnnotation);
            lines.push(`  test('${safeScenarioTitle}', async ({ page }) => {`);

            scenario.steps.forEach((step, i) => {
                lines.push(`    // Step ${i + 1}: ${step}`);
                lines.push(`    // await page.locator('SELECTOR').click();`);
            });

            lines.push('');
            lines.push(`    // Assertion: ${scenario.expected}`);
            lines.push(`    // await expect(page.locator('SELECTOR')).toBeVisible();`);
            lines.push(`  });`);
            lines.push('');
        });

        lines.push('});');

        return lines.join('\n');
    }
}
